# SPDX-License-Identifier: MIT
"""CLI: office artifact delivery."""

from __future__ import annotations

import argparse
import json

from .office import deliver_bundle


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(prog="office_cli")
    p.add_argument("--out", default="artifacts/office_bundle")
    p.add_argument("--title", default="WorkBuddy Report")
    p.add_argument("--body", default="Generated by octop.contrib.workbuddy.office")
    args = p.parse_args(argv)
    results = deliver_bundle(
        args.out,
        title=args.title,
        body=args.body,
        table_rows=[("item", "qty", "note"), ("A", 1, "ok"), ("B", 2, "ok")],
        slides=[("Overview", args.body), ("Next", "Ship and verify")],
    )
    print(json.dumps([r.to_dict() for r in results], ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
