-- Greenfield schema: integer surrogate PK on every table; business IDs are UNIQUE columns.
--
-- Portability notes (SQLite today → PostgreSQL later):
--   INTEGER PK AUTOINCREMENT  →  GENERATED BY DEFAULT AS IDENTITY
--   TEXT                      →  TEXT (unchanged)
--   INTEGER booleans (0/1)    →  BOOLEAN or SMALLINT
--   BLOB                      →  BYTEA
--   PRAGMA foreign_keys       →  omitted (enabled by default in PG)
--   Partial unique indexes    →  supported in both
--   ON CONFLICT … excluded    →  ON CONFLICT … EXCLUDED (same semantics)

PRAGMA foreign_keys = ON;

-- ── Users & agents ───────────────────────────────────────────────────────────

CREATE TABLE users (
  id                  INTEGER PRIMARY KEY AUTOINCREMENT,
  username            TEXT UNIQUE NOT NULL,
  password_hash       TEXT NOT NULL,
  role                TEXT NOT NULL,
  display_name        TEXT,
  disabled            INTEGER NOT NULL DEFAULT 0,
  locale              TEXT NOT NULL DEFAULT 'zh',
  created_at          INTEGER NOT NULL,
  login_failed_count  INTEGER NOT NULL DEFAULT 0,
  login_locked_until  INTEGER NOT NULL DEFAULT 0,
  preferences_json    TEXT NOT NULL DEFAULT '{}'
);

CREATE TABLE agents (
  id              INTEGER PRIMARY KEY AUTOINCREMENT,
  agent_id        TEXT NOT NULL UNIQUE,
  user_id         INTEGER REFERENCES users(id) ON DELETE CASCADE,
  name            TEXT NOT NULL,
  description     TEXT,
  persona_mbti    TEXT,
  default_model   TEXT,
  system_prompt   TEXT,
  enabled         INTEGER NOT NULL DEFAULT 1,
  config_json     TEXT,
  last_state      TEXT,
  last_error      TEXT,
  icon            TEXT,
  template_name   TEXT,
  created_at      INTEGER NOT NULL,
  updated_at      INTEGER NOT NULL
);
CREATE UNIQUE INDEX idx_agents_user_name ON agents(user_id, name) WHERE user_id IS NOT NULL;

-- ── Model & voice providers ──────────────────────────────────────────────────

CREATE TABLE providers (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  name        TEXT NOT NULL UNIQUE,
  kind        TEXT NOT NULL,
  base_url    TEXT,
  api_key     TEXT,
  extra_json  TEXT,
  models_json TEXT,
  note        TEXT,
  enabled     INTEGER NOT NULL DEFAULT 1,
  created_at  INTEGER NOT NULL,
  updated_at  INTEGER NOT NULL
);

CREATE TABLE voice_providers (
  id           INTEGER PRIMARY KEY AUTOINCREMENT,
  name         TEXT NOT NULL UNIQUE,
  kind         TEXT NOT NULL,
  capability   TEXT NOT NULL,
  base_url     TEXT,
  api_key      TEXT,
  extra_json   TEXT,
  note         TEXT,
  enabled      INTEGER NOT NULL DEFAULT 1,
  created_at   INTEGER NOT NULL,
  updated_at   INTEGER NOT NULL
);

-- ── Channels, cron, sessions & threads ───────────────────────────────────────

CREATE TABLE channels (
  id              INTEGER PRIMARY KEY AUTOINCREMENT,
  channel_id      TEXT NOT NULL UNIQUE,
  agent_id        TEXT NOT NULL REFERENCES agents(agent_id) ON DELETE CASCADE,
  user_id         INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  kind            TEXT NOT NULL,
  name            TEXT NOT NULL,
  config_json     TEXT NOT NULL,
  enabled         INTEGER NOT NULL DEFAULT 1,
  created_at      INTEGER NOT NULL,
  updated_at      INTEGER NOT NULL,
  UNIQUE(agent_id, name)
);

CREATE TABLE cron_jobs (
  id              INTEGER PRIMARY KEY AUTOINCREMENT,
  cron_id         TEXT NOT NULL UNIQUE,
  agent_id        TEXT NOT NULL REFERENCES agents(agent_id) ON DELETE CASCADE,
  user_id         INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  schedule_spec   TEXT NOT NULL,
  prompt          TEXT NOT NULL,
  session_key     TEXT NOT NULL,
  model           TEXT,
  fresh_thread    INTEGER NOT NULL DEFAULT 0,
  task_type       TEXT NOT NULL DEFAULT 'agent' CHECK (task_type IN ('text', 'agent')),
  enabled         INTEGER NOT NULL DEFAULT 1,
  last_run_at     INTEGER,
  last_status     TEXT,
  last_error      TEXT,
  created_at      INTEGER NOT NULL,
  updated_at      INTEGER NOT NULL
);

CREATE TABLE sessions (
  id                  INTEGER PRIMARY KEY AUTOINCREMENT,
  session_key         TEXT NOT NULL UNIQUE,
  agent_id            TEXT NOT NULL REFERENCES agents(agent_id) ON DELETE CASCADE,
  user_id             INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  channel_type        TEXT NOT NULL,
  chat_type           TEXT NOT NULL DEFAULT 'dm',
  thread_id           TEXT NOT NULL,
  updated_at          INTEGER NOT NULL,
  channel_subject_id  TEXT,
  channel_chat_type   TEXT NOT NULL DEFAULT 'dm',
  channel_metadata    TEXT,
  unread_count        INTEGER NOT NULL DEFAULT 0,
  channel_id          TEXT
);
CREATE INDEX idx_sessions_agent ON sessions(agent_id);
CREATE INDEX idx_sessions_channel ON sessions(channel_id) WHERE channel_id IS NOT NULL;

CREATE TABLE threads (
  id              INTEGER PRIMARY KEY AUTOINCREMENT,
  thread_id       TEXT NOT NULL UNIQUE,
  agent_id        TEXT NOT NULL REFERENCES agents(agent_id) ON DELETE CASCADE,
  user_id         INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  channel_type    TEXT NOT NULL,
  session_key     TEXT NOT NULL,
  title           TEXT,
  pinned          INTEGER NOT NULL DEFAULT 0,
  last_active     INTEGER NOT NULL,
  created_at      INTEGER NOT NULL
);
CREATE INDEX idx_threads_agent_active ON threads(agent_id, last_active DESC);
CREATE INDEX idx_threads_session ON threads(session_key);

-- ── Connectors ───────────────────────────────────────────────────────────────

CREATE TABLE connectors (
  id                    INTEGER PRIMARY KEY AUTOINCREMENT,
  instance_id           TEXT NOT NULL UNIQUE,
  user_id               INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  kind                  TEXT NOT NULL,
  display_name          TEXT NOT NULL,
  status                TEXT NOT NULL DEFAULT 'active',
  mcp_server_name       TEXT NOT NULL UNIQUE,
  credential_blob       BLOB,
  credential_expires_at INTEGER,
  credential_rotated_at INTEGER,
  config_json           TEXT,
  created_at            INTEGER NOT NULL,
  updated_at            INTEGER NOT NULL,
  UNIQUE(user_id, kind)
);
CREATE INDEX idx_connectors_user ON connectors(user_id);

CREATE TABLE connector_oauth_states (
  id              INTEGER PRIMARY KEY AUTOINCREMENT,
  state_id        TEXT NOT NULL UNIQUE,
  state           TEXT NOT NULL UNIQUE,
  user_id         INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  kind            TEXT NOT NULL,
  code_verifier   TEXT NOT NULL,
  redirect_after  TEXT,
  created_at      INTEGER NOT NULL
);

-- ── Usage, settings & storage ────────────────────────────────────────────────

CREATE TABLE usage_log (
  id              INTEGER PRIMARY KEY AUTOINCREMENT,
  ts              INTEGER NOT NULL,
  agent_id        TEXT NOT NULL REFERENCES agents(agent_id) ON DELETE CASCADE,
  user_id         INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  thread_id       TEXT NOT NULL DEFAULT '',
  model           TEXT NOT NULL DEFAULT '',
  input_tokens    INTEGER NOT NULL DEFAULT 0,
  output_tokens   INTEGER NOT NULL DEFAULT 0,
  total_tokens    INTEGER NOT NULL DEFAULT 0,
  source          TEXT NOT NULL DEFAULT 'chat'
);
CREATE INDEX idx_usage_log_ts ON usage_log(ts);
CREATE INDEX idx_usage_log_user ON usage_log(user_id, ts);
CREATE INDEX idx_usage_log_agent ON usage_log(agent_id, ts);
CREATE INDEX idx_usage_log_thread ON usage_log(thread_id, ts);

CREATE TABLE settings (
  key   TEXT PRIMARY KEY,
  value TEXT NOT NULL
);

INSERT INTO settings(key, value) VALUES ('active_stt_provider', 'browser');
INSERT INTO settings(key, value) VALUES ('active_tts_provider', 'browser');

CREATE TABLE storage_backends (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  name        TEXT NOT NULL UNIQUE,
  kind        TEXT NOT NULL,
  endpoint    TEXT,
  access_key  TEXT,
  secret_key  TEXT,
  bucket      TEXT,
  region      TEXT,
  config_json TEXT,
  note        TEXT,
  enabled     INTEGER NOT NULL DEFAULT 1,
  created_at  INTEGER NOT NULL,
  updated_at  INTEGER NOT NULL
);

-- ── Secrets & audit ──────────────────────────────────────────────────────────

CREATE TABLE secrets (
  k          TEXT PRIMARY KEY,
  v          BLOB NOT NULL,
  created_at INTEGER NOT NULL,
  rotated_at INTEGER
);

CREATE TABLE audit_log (
  id      INTEGER PRIMARY KEY AUTOINCREMENT,
  ts      INTEGER NOT NULL,
  actor   TEXT,
  action  TEXT NOT NULL,
  target  TEXT,
  payload TEXT
);
CREATE INDEX idx_audit_ts ON audit_log(ts);
CREATE INDEX idx_audit_actor ON audit_log(actor, ts);
CREATE INDEX idx_audit_action ON audit_log(action, ts);
CREATE INDEX idx_audit_target ON audit_log(target, ts);

-- ── Proactive care ───────────────────────────────────────────────────────────

CREATE TABLE proactive_care_config (
  agent_id             TEXT PRIMARY KEY REFERENCES agents(agent_id) ON DELETE CASCADE,
  enabled              INTEGER NOT NULL DEFAULT 1,    -- 0=false, 1=true
  active_hours_start   TEXT NOT NULL DEFAULT '09:00', -- HH:MM
  active_hours_end     TEXT NOT NULL DEFAULT '22:00', -- HH:MM
  min_interval_hours   INTEGER NOT NULL DEFAULT 5,
  max_interval_hours   INTEGER NOT NULL DEFAULT 24,
  updated_at           INTEGER NOT NULL
);

CREATE TABLE care_push_records (
  id          TEXT PRIMARY KEY,   -- UUID
  agent_id    TEXT NOT NULL,
  session_key TEXT NOT NULL,
  episode_id  TEXT NOT NULL,      -- 对应 Episode.id
  pushed_at   INTEGER NOT NULL    -- unix timestamp
);

CREATE INDEX idx_care_push_agent_episode ON care_push_records(agent_id, episode_id, pushed_at);
CREATE INDEX idx_care_push_agent_pushed  ON care_push_records(agent_id, pushed_at);

-- ── Schema version ───────────────────────────────────────────────────────────

CREATE TABLE _schema_version (version INTEGER NOT NULL);
INSERT INTO _schema_version(version) VALUES (1);
