-- One-time user invite codes (admin-issued; public redeem).

CREATE TABLE IF NOT EXISTS user_invites (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code              TEXT NOT NULL UNIQUE,
  created_by        BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  note              TEXT,
  created_at        BIGINT NOT NULL,
  expires_at        BIGINT NOT NULL,
  used_at           BIGINT,
  used_by_user_id   BIGINT REFERENCES users(id) ON DELETE SET NULL,
  revoked_at        BIGINT
);

CREATE INDEX IF NOT EXISTS idx_user_invites_created_at ON user_invites(created_at DESC);

UPDATE _schema_version SET version = 9;
