-- Schema v14: per-user policies (resource rows; missing/disabled = default).
-- Also: expert composer defaults (knowledge bases + connectors) on agents.

ALTER TABLE agents ADD COLUMN IF NOT EXISTS knowledge_base_ids TEXT;
ALTER TABLE agents ADD COLUMN IF NOT EXISTS mcp_servers TEXT;

CREATE TABLE user_policies (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  policy_id  TEXT    NOT NULL UNIQUE,
  user_id    BIGINT  NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name       TEXT    NOT NULL,
  enabled    INTEGER NOT NULL DEFAULT 1,
  value      TEXT    NOT NULL DEFAULT '',
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL,
  UNIQUE(user_id, name)
);

UPDATE _schema_version SET version = 14;
