-- Schema v15: per-agent ACL (explicit collaborators).
-- Same model as 015_agent_acl.sql; uses BIGINT / IDENTITY for PostgreSQL.

CREATE TABLE agent_acl (
  id         BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agent_id   TEXT    NOT NULL REFERENCES agents(agent_id) ON DELETE CASCADE,
  user_id    BIGINT  REFERENCES users(id) ON DELETE CASCADE,
  role       TEXT    NOT NULL CHECK (role IN ('viewer', 'editor')),
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL,
  UNIQUE(agent_id, user_id)
);

CREATE UNIQUE INDEX idx_agent_acl_public
  ON agent_acl (agent_id)
  WHERE user_id IS NULL;

INSERT INTO agent_acl (agent_id, user_id, role, created_at, updated_at)
SELECT agent_id, NULL, 'viewer', created_at, updated_at
FROM agents
WHERE is_shared = 1;

UPDATE _schema_version SET version = 15;
