-- Schema v16 (PostgreSQL): credit accounts and ledger.
-- Same model as 016_credits.sql; uses BIGINT and GENERATED BY DEFAULT AS IDENTITY.

CREATE TABLE credit_account (
  user_id                    BIGINT  PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  balance                    BIGINT  NOT NULL DEFAULT 0,
  total_earned               BIGINT  NOT NULL DEFAULT 0,
  total_spent                BIGINT  NOT NULL DEFAULT 0,
  tier                       TEXT    NOT NULL DEFAULT 'free'
                             CHECK (tier IN ('free', 'basic', 'pro', 'enterprise')),
  tier_name                  TEXT    NOT NULL DEFAULT 'Free',
  monthly_allowance          BIGINT  NOT NULL DEFAULT 0,
  monthly_used               BIGINT  NOT NULL DEFAULT 0,
  monthly_window_start       BIGINT,
  next_reset_at              BIGINT,
  updated_at                 BIGINT  NOT NULL
);

CREATE TABLE credit_ledger (
  id           BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id      BIGINT  NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  kind         TEXT    NOT NULL CHECK (kind IN ('spend', 'earn', 'recharge', 'gift', 'refund')),
  amount       BIGINT  NOT NULL,
  description  TEXT    NOT NULL DEFAULT '',
  category     TEXT,
  ref_id       TEXT,
  metadata     TEXT,
  ts           BIGINT  NOT NULL
);

CREATE INDEX idx_credit_ledger_user_ts ON credit_ledger (user_id, ts DESC);
CREATE INDEX idx_credit_ledger_kind   ON credit_ledger (user_id, kind, ts DESC);

UPDATE _schema_version SET version = 16;
